- name: Commit and push changes
            run: |
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add skins_data.json || true
              git diff --quiet && git diff --staged --quiet || git commit -m "Automated update: laby.net skins data"
              git push
